### ISSUE TITLE
Breadcrumb is breaking 

### ISSUE THREAD

**Issue by kundanrock** [NuCivic/dkan#1822]
Hi,

Breadcrumb is breaking. 
![break breadcrumb](https://cloud.githubusercontent.com/assets/4241992/24401241/3338522e-13d1-11e7-9b87-f4da7d3ea811.png)

**Comment by dafeder** [comment]
Hi @kundanrock - going to need way more information than that to help you. What version are you running, on what kind of environment, in what language, etc?

**Comment by kundanrock** [comment]
Hi @dafeder  We have used  dkan for drupal 7. We are running it for PHP (Drupal) , apache webserver and  ubuntu as operating system.

**Comment by dafeder** [comment]
Do you have this site on a public server I can look at? Still not enough info to diagnose

**Comment by kundanrock** [comment]
yes.. 
 http://open-data-telangana.azri.de/

**Comment by acouch** [comment]
@kundanrock Somehow your theme stylesheet got messed up. All of those characters are coming from the stylesheet: http://open-data-telangana.azri.de/profiles/dkan/themes/nuboot_radix/assets/css/nuboot_radix.style.css

See:

```css
/* Font Awesome uses the Unicode Private Use Area (PUA) to ensure screen
   readers do not read off random characters that represent icons */
.fa-glass:before {
  content: "ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ"; }
```

I'm not sure how that could have happened. It might be yr webserver unicode settings? Someone maybe opened and saved the file in an non-unicode compliant editor? @janette might have some insight.
