### ISSUE TITLE
User Menu colors should only apply when in navbar region

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/dkan#690]
The dkan sitewide user menu is set to make the links white no matter where it is placed.

This makes the links invisible if you move the user menu to the footer, for example.

Instead of 

``` css
#block-dkan-sitewide-dkan-sitewide-user-menu .links a {
  color: white;
}
```

it should include the selector that sets the dark background color like: 

``` css
.navigation-wrapper #block-dkan-sitewide-dkan-sitewide-user-menu .links a {
  color: white;
}
```
